### ISSUE TITLE
Can't group by result of a named function

### ISSUE THREAD

**Issue by br3nt** [rails/arel#383] opened 2015-07-25 08:41 UTC
I'm getting `NoMethodError: undefined method`relation' for #Arel::Nodes::NamedFunction:0x7633` when trying to group by the results of a named function.

``` ruby
class Appointment < ActiveRecord::Base
  scope :group_by_date, -> { group(date_column) }

  def self.date_column
    Arel::Nodes::NamedFunction.new(:date, [Appointment.arel_table[:start_time]], 'date')
  end
end

Appointment.group_by_date.count
# results in NoMethodError: undefined method `relation' for #<Arel::Nodes::NamedFunction:0x7633>
```

This seems perfectly reasonable, so I'm not sure why it's creating an error.  I'm pretty sure this was was possible in earlier versions of rails.

Is this a bug or is there a new way to convert a `Arel::Nodes::NamedFunction` to `Arel::Attributes::Attribute` for use in a query?

Environment: rails (4.1.8), activerecord (4.1.8), arel (5.0.1.20140414130214)

**Comment by mikz** [comment] 2015-12-08 15:35
Got hit by this. Is there an easy way to fix this?

**Comment by br3nt** [comment] 2015-12-09 23:14
Not that I found :-/.

Could potentially hack `Arel::Nodes::NamedFunction` and give it a `relation` method that returns whatever is being expected.  But that seems like a fragile fix.

**Comment by martinstreicher** [comment] 2017-02-14 16:32
I ran into a similar issue. What is interesting is that the SQL produced seems reasonable...

Imagine that `method` is `maximum` in the code below. 

```
sql = select(
      [
        table[:value].send(method).as(method),
         Arel::Nodes::NamedFunction.new('DATE', [table[:captured_at]]).as('date')
      ]
    )
    .where(table[:participant_id].eq(participant.id))
    .where(table[:prompt_id].in(prompt_ids))
    .group(Arel::Nodes::NamedFunction.new('DATE', [table[:captured_at]]))
    .to_sql
```

The SQL produced is ... 

```
SELECT MAX(\"responses\".\"value\") AS maximum, DATE(\"responses\".\"captured_at\") AS date
FROM \"responses\" 
WHERE \"responses\".\"participant_id\" = 37 AND \"responses\".\"prompt_id\" IN (7, 8)
GROUP BY DATE(\"responses\".\"captured_at\")"
```

And that produces the proper answers.

**Comment by rafaelfranca** [comment] 2017-02-24 00:03
You are trying to use arel API in Active Record API and since arel is a private API that may not work.

**Comment by martinstreicher** [comment] 2017-02-27 20:48
If I use only Arel to compose the same query, I still get an error. I think this is a valid bug.

**Comment by martinstreicher** [comment] 2017-04-25 19:21
@br3nt Are you seeing this error inside Active Admin or from a regular query? I have something similar: I see the error you mention in ActiveAdmin when trying to get an index page; however, if I run the same query from the console, it works just fine. ActiveAdmin is piling on additional scopes and filters and may be adding something that later breaks AR. 

In my case, I see that `column_alias_for` is getting an `Arel::Nodes::NamedFunction` rather than an `Arel::Attributes::Attribute`. The former contains the latter, but even if I hack to pick that out, things still die in the actual walk of the Arel.

**Comment by mikz** [comment] 2018-04-13 14:12
My workaround is to call `#to_sql` on the `Arel::Nodes::NamedFunction` like `.group(function.to_sql)`.

**Comment by matthewd** [comment] 2018-04-25 08:12
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)

**Closed by matthewd** 2018-04-25 08:12 UTC
