### ISSUE TITLE
NamedFunction doesn't accept -Float::INFINITY

### ISSUE THREAD

**Issue by filipegiusti** [rails/arel#387] opened 2015-07-30 15:21 UTC
-Float::INFINITY works in comparisons but not in named functions.

``` ruby
Arel::Attributes::Attribute.new(Arel::Table.new("a"), "b").gt(-Float::INFINITY).to_sql
# "a"."b" > '-Infinity'

Arel::Nodes::NamedFunction.new('COALESCE', [-Float::INFINITY]).to_sql
# RuntimeError: unsupported: Float

infinity = Arel::Nodes::Casted.new(-Float::INFINITY, nil)
Arel::Nodes::NamedFunction.new('COALESCE', [infinity]).to_sql
# COALESCE('-Infinity')
```

**Comment by vipulnsward** [comment] 2015-11-29 17:54
@filipegiusti not sure what the issue is here. `#gt` method here, quotes values automatically. 
`NameFunction` does not try to handle this complexity. Passing `Quoted` value to `NamedFunction` works right now.

**Comment by filipegiusti** [comment] 2015-11-30 19:22
If that's not a good feature to have, then the maintainer can close this issue. Although having this difference in the parameters causes some confusion.

**Comment by matthewd** [comment] 2018-04-25 08:13
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)

**Closed by matthewd** 2018-04-25 08:13 UTC
