### ISSUE TITLE
 incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by MasahiroMorita** [rails/arel#389] opened 2015-08-18 09:10 UTC
Hello! I'm trying to save a record into MySQL, but it raise the following error.

The data I want to insert into record is just a text written in UTF-8 (Japanese), and this error is occur in some specific case, which is a column consisted of both ASCII and UTF-8 character. The other case, like the column consisted of only UTF-8 or ASCII character, it success. It is very mysterious... :-p

How to solve this issue?
thank you.

```
An Encoding::CompatibilityError occurred in background at 2015-08-18 17:50:38 +0900 :

 incompatible character encodings: UTF-8 and ASCII-8BIT
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:109:in `join&#x27;

 -------------------------------
Backtrace:
-------------------------------

 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:109:in `join'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:109:in `visit_Arel_Nodes_Values'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:19:in `visit'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:74:in `visit_Arel_Nodes_InsertStatement'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:19:in `visit'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:5:in `accept'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:19:in `accept'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/arel-3.0.3/lib/arel/visitors/bind_visitor.rb:11:in `accept'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/database_statements.rb:7:in `to_sql'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/database_statements.rb:89:in `insert'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/relation.rb:66:in `insert'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/persistence.rb:367:in `create'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/timestamp.rb:58:in `create'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/callbacks.rb:268:in `block in create'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:403:in `_run__158473759337365815__create__4322412957035373571__callbacks'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `__run_callback'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_create_callbacks'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/callbacks.rb:268:in `create'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/persistence.rb:348:in `create_or_update'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/callbacks.rb:264:in `block in create_or_update'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:447:in `_run__158473759337365815__save__4322412957035373571__callbacks'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `__run_callback'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/callbacks.rb:264:in `create_or_update'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/persistence.rb:104:in `save!'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/validations.rb:56:in `save!'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/transactions.rb:264:in `block in save!'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/transactions.rb:208:in `transaction'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/postamt-0.9.2/lib/postamt.rb:73:in `block in transaction'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/postamt-0.9.2/lib/postamt.rb:19:in `on'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/postamt-0.9.2/lib/postamt.rb:73:in `transaction'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.1.88/lib/new_relic/agent/method_tracer.rb:523:in `block in transaction_with_trace_ActiveRecord_self_name_transaction'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.1.88/lib/new_relic/agent/method_tracer.rb:273:in `trace_execution_scoped'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.1.88/lib/new_relic/agent/method_tracer.rb:518:in `transaction_with_trace_ActiveRecord_self_name_transaction'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/transactions.rb:264:in `save!'
 /var/www/gamba-v2/releases/20150818075840/app/api/v3/diaries.rb:83:in `block (3 levels) in <class:Diaries>'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/transactions.rb:208:in `transaction'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/postamt-0.9.2/lib/postamt.rb:73:in `block in transaction'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/postamt-0.9.2/lib/postamt.rb:19:in `on'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/postamt-0.9.2/lib/postamt.rb:73:in `transaction'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.1.88/lib/new_relic/agent/method_tracer.rb:523:in `block in transaction_with_trace_ActiveRecord_self_name_transaction'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.1.88/lib/new_relic/agent/method_tracer.rb:273:in `trace_execution_scoped'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.1.88/lib/new_relic/agent/method_tracer.rb:518:in `transaction_with_trace_ActiveRecord_self_name_transaction'
 /var/www/gamba-v2/releases/20150818075840/app/api/v3/diaries.rb:82:in `block (2 levels) in <class:Diaries>'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/grape-0.12.0/lib/grape/endpoint.rb:47:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/grape-0.12.0/lib/grape/endpoint.rb:47:in `block in generate_api_method'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/grape-0.12.0/lib/grape/endpoint.rb:247:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/grape-0.12.0/lib/grape/endpoint.rb:247:in `run'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/grape-0.12.0/lib/grape/endpoint.rb:195:in `block in call!'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/grape-0.12.0/lib/grape/middleware/base.rb:24:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/grape-0.12.0/lib/grape/middleware/base.rb:24:in `call!'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/grape-0.12.0/lib/grape/middleware/base.rb:18:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/grape-0.12.0/lib/grape/middleware/base.rb:24:in `call!'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/grape-0.12.0/lib/grape/middleware/base.rb:18:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/grape-0.12.0/lib/grape/middleware/error.rb:27:in `block in call!'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/grape-0.12.0/lib/grape/middleware/error.rb:26:in `catch'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/grape-0.12.0/lib/grape/middleware/error.rb:26:in `call!'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/grape-0.12.0/lib/grape/middleware/base.rb:18:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/head.rb:9:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:134:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/grape-0.12.0/lib/grape/endpoint.rb:196:in `call!'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/grape-0.12.0/lib/grape/endpoint.rb:184:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:152:in `block in call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `block in recognize'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:68:in `optimized_each'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:95:in `recognize'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:141:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/grape-0.12.0/lib/grape/api.rb:98:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/grape-0.12.0/lib/grape/api.rb:33:in `call!'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/grape-0.12.0/lib/grape/api.rb:29:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/routing/route_set.rb:601:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/jquery-fileupload-rails-0.4.1/lib/jquery/fileupload/rails/middleware.rb:14:in `_call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/jquery-fileupload-rails-0.4.1/lib/jquery/fileupload/rails/middleware.rb:10:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.1.88/lib/new_relic/rack/error_collector.rb:12:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.1.88/lib/new_relic/rack/agent_hooks.rb:18:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.1.88/lib/new_relic/rack/browser_monitoring.rb:16:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/exception_notification-3.0.1/lib/exception_notifier.rb:41:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/config.rb:12:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/conditionalget.rb:35:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/head.rb:14:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/bundler/gems/jpmobile-1e69d9e603a5/lib/jpmobile/rack/mobile_carrier.rb:13:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/flash.rb:242:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/cookies.rb:341:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/query_cache.rb:64:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `_run__3524552116919744736__call__4322412957035373571__callbacks'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `__run_callback'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/rack/logger.rb:32:in `call_app'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/rack/logger.rb:16:in `block in call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/tagged_logging.rb:22:in `tagged'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/rack/logger.rb:16:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/request_id.rb:22:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/static.rb:62:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:143:in `pass'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:155:in `invalidate'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:71:in `call!'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/engine.rb:479:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/application.rb:223:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:576:in `process_client'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670:in `worker_loop'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.1.88/lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:22:in `call'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.1.88/lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:22:in `block (4 levels) in <top (required)>'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:140:in `start'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/bin/unicorn:23:in `load'
 /var/www/gamba-v2/shared/bundle/ruby/1.9.1/bin/unicorn:23:in `<main>'
```

**Comment by vipulnsward** [comment] 2015-11-29 17:47
@MasahiroMorita this is a very old version of the gem you are using. Please try using newer version, as well as new ruby version if possible.

**Comment by mariohmol** [comment] 2016-06-10 14:39
I'm havin this with arel-4.0.2 , any ideas how to fix it?

**Comment by mariohmol** [comment] 2016-06-10 14:53
In my canse, the problem seems to be  ` . I had that in a text field, after removing that, it worked!

Any ideas how to solve that?

**Comment by MasahiroMorita** [comment] 2016-06-11 08:33
Finally I solved this.
Try `force_encoding`, like:
```
  a_property = param[:property].force_encoding('utf-8')
```

**Comment by matthewd** [comment] 2018-04-25 08:13
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)

**Closed by matthewd** 2018-04-25 08:13 UTC
